SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [preODS].[Appetize_Vendor]
AS

SELECT DISTINCT

	CONVERT(int,[L1_id]) [Vendor_id_K]
	,CONVERT(NVARCHAR(50),[ext_vendor_id]) [ext_vendor_id]
	,CONVERT(NVARCHAR(100),[username]) [username]
	,CONVERT(NVARCHAR(50),[printer_ip]) [printer_ip]
	,CONVERT(int,[venue_id]) [venue_id]
	,CONVERT(NVARCHAR(100),[name]) [name]
	,CONVERT(int,[staff_members]) [staff_members]
	,CONVERT(int,[order_capacity]) [order_capacity]
	,CONVERT(int,[fast_pass_lane]) [fast_pass_lane]
	,CONVERT(int,[vendor_status]) [vendor_status]
	,CONVERT(int,[status]) [status]
	,CONVERT(NVARCHAR(250),[status_description]) [status_description]
	,CONVERT(int,[drink_limit]) [drink_limit]
	,CONVERT(int,[promo_enabled]) [promo_enabled]
	,CONVERT(int,[pickup_increment]) [pickup_increment]
	,CONVERT(int,[wait_m]) [wait_m]
	,CONVERT(NVARCHAR(250),[welcome_text]) [welcome_text]
	,CONVERT(NVARCHAR(250),[pickup_location]) [pickup_location]
	,CONVERT(NVARCHAR(250),[additional_info]) [additional_info]
	,CONVERT(NVARCHAR(100),[first_screen]) [first_screen]
	,CONVERT(int,[login_required]) [login_required]
	,CONVERT(int,[tip_enabled]) [tip_enabled]
	,CONVERT(int,[fee]) [fee]
	,CONVERT(int,[fee_in_percent]) [fee_in_percent]
	,CONVERT(int,[convince_fee]) [convince_fee]
	,CONVERT(NVARCHAR(250),[fee_text]) [fee_text]
	,CONVERT(decimal(18,2),[collected_tax_rate]) [collected_tax_rate]
	,CONVERT(int,[tax_on_fee]) [tax_on_fee]
	,CONVERT(int,[taxOnConvenienceFee]) [taxOnConvenienceFee]
	,CONVERT(nvarchar(max),[image_url]) [image_url]
	,CONVERT(int,[vendor_type]) [vendor_type]
	,CONVERT(int,[seat_confirmation]) [seat_confirmation]
	,CONVERT(decimal(18,2),[tare_weight]) [tare_weight]
	,CONVERT(int,[food_count]) [food_count]
	,CONVERT(int,[drink_count]) [drink_count]
	,CONVERT(int,[mixer_count]) [mixer_count]
	,CONVERT(int,[mixer_built_count]) [mixer_built_count]
	,CONVERT(int,[merch_count]) [merch_count]
	,CONVERT(int,[bundle_count]) [bundle_count]
	,CONVERT(int,[pickupTimeSelectionEnabled]) [pickupTimeSelectionEnabled]
	,CONVERT(int,[tax_on_total]) [tax_on_total]
	,CONVERT(int,[tax_on_tip]) [tax_on_tip]
	,CONVERT(int,[tax_charge_after_discount]) [tax_charge_after_discount]
	,CONVERT(int,[quick_order_view]) [quick_order_view]
	,CONVERT(NVARCHAR(MAX),[quick_order_image]) [quick_order_image]
	,CONVERT(NVARCHAR(250),[groups]) [groups]
	,CONVERT(int,[is_drink_limit_per_event]) [is_drink_limit_per_event]
	,CONVERT(int,[pickupIncrement]) [pickupIncrement]
	,CONVERT(int,[isAlcoholLimitPerEventEnabled]) [isAlcoholLimitPerEventEnabled]
	,CONVERT(int,[alcoholLimitPerEvent]) [alcoholLimitPerEvent]
	,CONVERT(int,[isAlcoholLimitPerOrderEnabled]) [isAlcoholLimitPerOrderEnabled]
	,CONVERT(int,[alcoholLimitPerOrder]) [alcoholLimitPerOrder]
FROM [src].[Appetize_Vendor] WITH (NOLOCK)
GO
