CREATE TABLE [dbo].[FD_DONATION_USAGE]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[DRIVE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[DONOR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SEQ] [bigint] NOT NULL,
[VMC] [bigint] NOT NULL,
[USAGE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USG_PLG_AMT] [numeric] (18, 2) NULL,
[USG_OUT_AMT] [numeric] (18, 2) NULL,
[USG_CASH_AMT] [numeric] (18, 2) NULL,
[USG_GIK_AMT] [numeric] (18, 2) NULL,
[USG_WO_AMT] [numeric] (18, 2) NULL,
[ZID] [varchar] (58) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_DONATION_USAGE] ADD CONSTRAINT [PK_FD_DONATION_USAGE] PRIMARY KEY CLUSTERED  ([ETLSID], [DRIVE], [DONOR], [SEQ], [VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_DONOR] ON [dbo].[FD_DONATION_USAGE] ([DONOR])
GO
CREATE NONCLUSTERED INDEX [IDX_DRIVE] ON [dbo].[FD_DONATION_USAGE] ([DRIVE])
GO
CREATE NONCLUSTERED INDEX [IDX_SEQ] ON [dbo].[FD_DONATION_USAGE] ([SEQ])
GO
CREATE NONCLUSTERED INDEX [IDX_USAGE] ON [dbo].[FD_DONATION_USAGE] ([USAGE])
GO
