CREATE TABLE [dbo].[FD_PROGRAM]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[PROGRAM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SEQ] [bigint] NULL,
[LIFETIME] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_PROGRAM] ADD CONSTRAINT [PK_FD_PROGRAM] PRIMARY KEY CLUSTERED  ([ETLSID], [PROGRAM])
GO
CREATE NONCLUSTERED INDEX [IDX_PROGRAM] ON [dbo].[FD_PROGRAM] ([PROGRAM])
GO
