CREATE TABLE [dbo].[FD_CAMPAIGN]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[CAMPAIGN] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROGRAM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[STATUS] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[START_DATE] [datetime] NULL,
[END_DATE] [datetime] NULL,
[CHAIRPERSON] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GOAL] [numeric] (18, 2) NULL,
[PREV_CAMPAIGN] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SEQ] [bigint] NULL,
[BASIS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[CLASS_LEVEL] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MATCHING_BASIS] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_CAMPAIGN] ADD CONSTRAINT [PK_FD_CAMPAIGN] PRIMARY KEY CLUSTERED  ([ETLSID], [CAMPAIGN])
GO
CREATE NONCLUSTERED INDEX [IDX_CAMPAIGN] ON [dbo].[FD_CAMPAIGN] ([CAMPAIGN])
GO
CREATE NONCLUSTERED INDEX [IDX_PROGRAM] ON [dbo].[FD_CAMPAIGN] ([PROGRAM])
GO
