CREATE TABLE [dbo].[Import_AClub_20180327_v2]
(
[First Name] [varchar] (17) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle Name] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Athlete Full Name] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Maiden Name] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Personal Title] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Address] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[State Province] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ZIP Postal Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sport] [varchar] (42) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Year Lettered] [varchar] (36) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home Phone] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coach] [varchar] (26) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[E-mail Address] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Graduation Year] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday] [datetime] NULL,
[Degree] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company] [varchar] (43) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company Address] [varchar] (19) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company City] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company State] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company Zip] [int] NULL,
[Company Email] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Company Phone] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Spouse] [varchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes for Reunion] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Country Region] [varchar] (13) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Job Title] [varchar] (38) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Mobile Number] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes] [varchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DegreeType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sent] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone - Other] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[College] [varchar] (48) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last Name] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
