CREATE TABLE [dbo].[FD_SOLICITOR]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[SOLICITOR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TEAM] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[MAIL_ADTYPE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[COMMENTS] [varchar] (4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_SOLICITOR] ADD CONSTRAINT [PK_FD_SOLICITOR] PRIMARY KEY CLUSTERED  ([ETLSID], [SOLICITOR])
GO
