CREATE TABLE [dbo].[FD_USAGE]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[FUND_USAGE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[NAME] [varchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ENTITY] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[RESTRICTED] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INACTIVITY] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LAST_USER] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LAST_DATETIME] [datetime] NULL,
[ZID] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_USAGE] ADD CONSTRAINT [PK_FD_USAGE] PRIMARY KEY CLUSTERED  ([ETLSID], [FUND_USAGE])
GO
CREATE NONCLUSTERED INDEX [IDX_FUND_USAGE] ON [dbo].[FD_USAGE] ([FUND_USAGE])
GO
