CREATE TABLE [dbo].[FD_TRANS_USAGE]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[TRANS_NO] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[USAGE] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[USG_PLG_AMT] [numeric] (18, 2) NULL,
[USG_OUT_AMT] [numeric] (18, 2) NULL,
[USG_DON_AMT] [numeric] (18, 2) NULL,
[USG_WO_AMT] [numeric] (18, 2) NULL,
[ZID] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_TRANS_USAGE] ADD CONSTRAINT [PK_FD_TRANS_USAGE] PRIMARY KEY CLUSTERED  ([ETLSID], [TRANS_NO], [VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_TRANS_NO] ON [dbo].[FD_TRANS_USAGE] ([TRANS_NO])
GO
CREATE NONCLUSTERED INDEX [IDX_USAGE] ON [dbo].[FD_TRANS_USAGE] ([USAGE])
GO
