CREATE TABLE [dbo].[FD_DONOR_PROGRAM]
(
[ETLSID] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CS_AS NOT NULL,
[DONOR] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[VMC] [bigint] NOT NULL,
[CLASS] [varchar] (32) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[PROGRAM] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CS_AS NULL,
[LIFETIME_DONATION] [numeric] (18, 2) NULL,
[LIFETIME_MATCH] [numeric] (18, 2) NULL,
[LIFETIME_DONOR] [varchar] (16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[YEAR] [bigint] NULL,
[ZID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SOURCE_ID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EXPORT_DATETIME] [datetime] NULL,
[ETL_Sync_DeltaHashKey] [binary] (32) NULL
)
GO
ALTER TABLE [dbo].[FD_DONOR_PROGRAM] ADD CONSTRAINT [PK_FD_DONOR_PROGRAM] PRIMARY KEY CLUSTERED  ([ETLSID], [DONOR], [VMC])
GO
CREATE NONCLUSTERED INDEX [IDX_CLASS] ON [dbo].[FD_DONOR_PROGRAM] ([CLASS])
GO
CREATE NONCLUSTERED INDEX [IDX_DONOR] ON [dbo].[FD_DONOR_PROGRAM] ([DONOR])
GO
CREATE NONCLUSTERED INDEX [IDX_PROGRAM] ON [dbo].[FD_DONOR_PROGRAM] ([PROGRAM])
GO
CREATE NONCLUSTERED INDEX [IDX_YEAR] ON [dbo].[FD_DONOR_PROGRAM] ([YEAR])
GO
