CREATE TABLE [ods].[Snapshot_Appetize_Vendor]
(
[Appetize_VendorSK] [int] NOT NULL IDENTITY(1, 1),
[Vendor_id] [int] NULL,
[ext_vendor_id] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[username] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[printer_ip] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[venue_id] [int] NULL,
[name] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[staff_members] [int] NULL,
[order_capacity] [int] NULL,
[fast_pass_lane] [int] NULL,
[vendor_status] [int] NULL,
[status] [int] NULL,
[status_description] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[drink_limit] [int] NULL,
[promo_enabled] [int] NULL,
[pickup_increment] [int] NULL,
[wait_m] [int] NULL,
[welcome_text] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[pickup_location] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[additional_info] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[first_screen] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[login_required] [int] NULL,
[tip_enabled] [int] NULL,
[fee] [int] NULL,
[fee_in_percent] [int] NULL,
[convince_fee] [int] NULL,
[fee_text] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[collected_tax_rate] [decimal] (18, 2) NULL,
[tax_on_fee] [int] NULL,
[taxOnConvenienceFee] [int] NULL,
[image_url] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[vendor_type] [int] NULL,
[seat_confirmation] [int] NULL,
[tare_weight] [decimal] (18, 2) NULL,
[food_count] [int] NULL,
[drink_count] [int] NULL,
[mixer_count] [int] NULL,
[mixer_built_count] [int] NULL,
[merch_count] [int] NULL,
[bundle_count] [int] NULL,
[pickupTimeSelectionEnabled] [int] NULL,
[tax_on_total] [int] NULL,
[tax_on_tip] [int] NULL,
[tax_charge_after_discount] [int] NULL,
[quick_order_view] [int] NULL,
[quick_order_image] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[groups] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[is_drink_limit_per_event] [int] NULL,
[pickupIncrement] [int] NULL,
[isAlcoholLimitPerEventEnabled] [int] NULL,
[alcoholLimitPerEvent] [int] NULL,
[isAlcoholLimitPerOrderEnabled] [int] NULL,
[alcoholLimitPerOrder] [int] NULL,
[ETL_CreatedOn] [datetime] NULL,
[ETL_CreatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETL_UpdatedOn] [datetime] NULL,
[ETL_UpdatedBy] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordEndDate] [datetime] NULL
)
GO
ALTER TABLE [ods].[Snapshot_Appetize_Vendor] ADD CONSTRAINT [PK__Snapshot__8B43C6B27A923CD0] PRIMARY KEY CLUSTERED  ([Appetize_VendorSK])
GO
